fix(ops/machines/build03): increase number of connections to nix-daemon.socket
Lix has been quite unstable for us, builds very frequently failed with

> error: cannot open connection to remote store 'daemon': error: read of 32768 bytes: Connection reset by peer

I reached out to some Lix developers about it, so far I haven't heard back.

Looking today again, I spotted the following in the logs:

> systemd[1]: nix-daemon.socket: Too many incoming connections (64), dropping connection.

It seems if unset the limit is 64, which is way too little for our
parallelism. Let's see if this improves things.

Change-Id: Ic23f7cbf14c73d05b1ee23dc2c58458caff3580e
Reviewed-on: https://cl.snix.dev/c/snix/+/31710
Tested-by: besadii
Reviewed-by: Vova Kryachko <v.kryachko@gmail.com>
Autosubmit: Florian Klink <flokli@flokli.de>