refactor(snix/eval): introduce ScopeGuards to track scope lifetimes
This introduces a data structure that represents the lifetime of a
scope. The `Scope::begin_scope` function returns an instance and the
`Scope::end_scope` function expects a matching value to be passed.

This helps two fold:
  * During development there is a variable that represents a scope.
    Since the ownership has to be passed back to the `Scope` instance it
    allows easier reasoning about which scopes are being opened/closed
    where. Scopes can also have names assigned to them (debug builds
    only).
  * In debug builds the order in which scopes are closed is asserted.
    If the order is violated the code panics. Same with scopes that are
    never closed.

While working on this I've fixed one issue where scopes weren't closed
but opened. It manifested like this once the debug assertions were in:

> thread 'main' (1076888) panicked at eval/src/compiler/scope.rs:429:9:
> assertion `left == right` failed: Snix bug: the scope `compile_attr_set::temporaries` was closed out of order. The guard is for depth 8 but was used to close 9.  left: 8
>  right: 9

Since not fixing the issue is now at least a compiler warning (unused
variable) it has been fixed as part of this commit.

Change-Id: I79a24d5b8f41f93bf6139869ee0847dc9677e2ba
Reviewed-on: https://cl.snix.dev/c/snix/+/31624
Tested-by: besadii
Reviewed-by: Florian Klink <flokli@flokli.de>
Autosubmit: Andreas Rammhold <andreas@rammhold.de>